### ISSUE TITLE
RFC: what postCSS plugins do we want to include.

### ISSUE THREAD

**Issue by tkh44** [tkh44/emotion#60]
Problem description:
We need a good set of default plugins to include. 

Suggested solution:
http://cssnext.io/ and http://simplaio.github.io/rucksack/ are the obvious choices. I think we want just some of the individual plugins from these, not the entire project.

@threepointone @mitchellhamilton

**Comment by souporserious** [comment]
I love all of these ideas 😍  I'd love to see a solid plugin system of some sorts for emotion or even glam. Since there are so many opinions around this stuff, I personally think it could help mitigate issues. Once the system is in place, in theory, anyone could write a transformer or whatever and handle whatever use case they need/want. Maybe that's too broad of thinking though 😅

From my understanding, it's using PostCSS right? So being able to tie into their plugin system somehow and write custom plugins or use the preexisting ones would be great.

For example, I'd love to write `margin-vertical`, but I know some people like the shorthand methods like `mv`. Instead of the library forming that opinion it would be cool to have a section of addons or something that you could implement at your own will. I hope that makes sense 😇 I've been using a library called [PopperJS](https://github.com/FezVrasta/popper.js) recently and the whole library is built on a plugin system and seems to work fairly well. I'd love to see that type of system for emotion or glam.

I'm also willing to help with whatever I can 😄  I'd love to help push this stuff forward and thank you for all of your hard work on this stuff and caring about it 🙏  I really appreciate it on my end.

**Comment by threepointone** [comment]
I think it's too early for a plugin system per se, and considering that most of our work is at compile time, I'm happy to have a 'blessed' set of additions from cssnext/rucksack for most of the 'major' usecases. Once that is in place, it should be relatively easy to expose a hook for advanced consumers to add a translation engine that compiles down to our format. 

(In general I believe plugin systems are an admission that the composition model is a failure, and I think we should put a good effort on solving for that before a plugin system)

**Comment by threepointone** [comment]
oh, and I totally prefer `margin-vertical` over `mv`.

**Comment by souporserious** [comment]
Totally makes sense 😊  thanks for explaining! I guess my biggest interest is being able to add something like this: https://gist.github.com/souporserious/a352fe9c4ae18518f1d38099201d673a#file-compute-design-system-js-L257-L264

Vertical rhythm is inherently hard on the web so being able to catch that and not have to think about it has been really nice in my current workflow. But again, this is my personal preference so I would love to be able to add this as a plugin or something. It sounds like I just need to be patient 💩 😆

**Comment by oliverturner** [comment]
If you're looking for specifics, here's a subset of the most used ones from cssnext:

- `postcss-import`
- `postcss-nested`
- `postcss-custom-media`
- `postcss-custom-properties`
- `postcss-color-function`
- `autoprefixer`

Obviously some of these are redundant in the context of Emotion (e.g. `postcss-custom-properties`) but I've included them for the sake of completeness.

**Comment by sylvainpolletvillard** [comment]
Would it be possible to use custom PostCSS plugins with emotion based on `postcss.config.js` ? So that anyone could have their own default set of plugins.

**Comment by leesiongchan** [comment]
`postcss-nested` is super important.

**Comment by tkh44** [comment]
@sylvainpolletvillard The only hard part about this is that the plugins have to be synchronous because babel is synchronous.

**Comment by thangngoc89** [comment]
Postcss used to support a synchronous API. Perhaps use old version of postcss?

**Comment by tkh44** [comment]
We are using a forked version from styled-components now that is synchronous. The plugins just have to be synchronous

**Comment by sylvainpolletvillard** [comment]
@tkh44 I asked the PostCSS team for help, maybe we can work this out :+1: can you give us more details about the reasoning behind it having to be synchronous, and link to the part of the source where postcss is called ? thanks

**Comment by thangngoc89** [comment]
@sylvainpolletvillard babel only offers synch API so everything must be sync.

**Comment by ai** [comment]
Hi. I very like the idea of `emotion` :).

@tkh44 can I help somehow with async plugins? I think the best way is to force Babel to have async plugins :D.

@sylvainpolletvillard also can we run PostCSS after `emotion`? As I understand Babel plugin move styles to separated CSS file, so we can run standard `postcss-loader` (without any limits of sync/async).

**Comment by tkh44** [comment]
@ai babel must be synchronous from what I understand.

> also can we run PostCSS after `emotion`?

you could do that. You can use whatever loaders you like.

**Comment by mitchellhamilton** [comment]
We might be able to use async plugins with [`deasync`](https://www.npmjs.com/package/deasync).

https://github.com/giuseppeg/styled-jsx-postcss/blob/master/src/babel.js#L107

**Comment by threepointone** [comment]
(Pssst we should also start work on writing our own parser okthxbai)

**Comment by HBCharles** [comment]
I was using postcss-font-magician. Does the fontface function could help me to replace this plugin ? Could you provide a complete example with components.
