### ISSUE TITLE
CSS extraction strategy discussion

### ISSUE THREAD

**Issue by tkh44** [tkh44/emotion#62]
via @threepointone:

- extract all static css no matter what. that gets 'import'-ed anyway, so that's good

- extract css with prop interpolations as well, because that gets imported too

- at runtime, if it's in a browser without support, use the inline mode function. else
    ```
   if has support, but <16, use .vars. 
   else, shiny new react functionality
  ```

 - css with apply/block interpolations has to be pure inline mode

**Comment by hamlim** [comment]
Static css extraction is something I definitely want to see working with inline mode to make SSR even better. I am going to mess around a bit within my fork of emotion to see if I can make a naive solution to get static css extraction working.

So far not sure if the way I am thinking of tackling this will cover some/any of the points noted above, but figured this is a good issue to use to track this kind of work.

I can open a WIP PR once I have something really basic working with a few test cases too.

That all being said any good advice on how people may want to see this solved would be greatly appreciated!

**Comment by tkh44** [comment]
@hamlim opening a wip pr would be awesome. I don't consider the code complete until that review button is hit or the checkbox is checked. I would rather we get more early prs that way we can make sure everyone is on the same page early in the process.

**Comment by hamlim** [comment]
So I opened a PR, however I don't know if it will/should fully cover this issue. Feel free to take a look at the PR and see if you agree.

I feel like to accomplish what this issue wants to accomplish would require a decent amount of more work, and I feel like I wouldn't be able to have a good enough grasp on the functionality of emotion overall to implement it properly. 

PR is here: https://github.com/tkh44/emotion/pull/121

**Comment by faceyspacey** [comment]
@tkh44 it looks like ur nailing it.

Does this:
> extract css with prop interpolations as well
mean you "extract" to where? You can't extract it to the same css files since it's javascript. Do you create a 2nd file that is javascript?

Either way, it sounds really good. Basically at a high level, you're finding the dynamic parts and keeping it in the js, while pushing anything static to css files.

The only thing I would add is this, and it might put a wrench in the current plan: basically you want to be able construct that static css semi-dynamically at build time. That way you can construct your rules via javascript.

The wrench that puts in the system is: *how do you know what is dynamic css and what is static css*? If truly dynamic css is always designated by a selector function (`props => style`), then you know that's "runtime dynamic." 

So the missing step in the build process would be evaluating the javascript that generates static css. That way you have the full power of javascript available to you.

**Comment by tkh44** [comment]
> extract css with prop interpolations as well, because that gets imported too

Its been 11 days. I'm not 100% sure what you meant by this either @threepointone
